id = "boavista"
name = "Boavista"
schema_version = 1
version = "0.0.2"
authors = ["José Duarte <duarte.gmj@gmail.com>"]
description = "The tear-free light theme!"
repository = "https://github.com/jmg-duarte/boavista-zed"
